Updates to Configurations for ICARUS MCP
SBNSoftware/icaruscode pull request #223
Opened 2021-08-03 14:09 UTC by gputnam

Updates to ICARUS MC reconstruction for the upcoming MCP.

Right now includes a bugfix in running the stage1 MC reco fcl file and includes a number of configurations to run "CAF" making.

This is intended as a draft PR to collect updates needed for the MCP.

2021-08-03 19:36 UTC, gputnam commented
Also linked: https://github.com/SBNSoftware/icarusalg/pull/34

2021-08-05 17:19 UTC, PetrilloAtWork commented
On Thursday, 5 August 2021 09:11:06 PDT Wesley Ketchum wrote:
> @wesketchum requested your review on: SBNSoftware/icaruscode#223 Updates to
> Configurations for ICARUS MCP.

Kind of conflict of interest here.
I should not be the only one reviewing, but I can concentrate on the parts I 
did not contribute to.

And let's see what happens when I try to answer to a GitHub notification e-
mail.

-- 
Gianluca Petrillo

SLAC building 084/B117, mail stop 78
Phone: +1 (650) 926-3088
E-mail: ***@***.***
Instant message: ***@***.*** (jabber)

2021-08-06 15:38 UTC, SFBayLaser commented
I think this is critical for the next release, not the current one (v09_28_00) and so will leave open. I think there is still more work for the MC versions of stage0 and stage1. TBC.

2021-08-09 21:43 UTC, brucehoward-physics commented
Pushing commit adding showers. Ran very small tests on a few particle gun MC events just to see that things ran basically. Possibly interestingly, in a test of a few events trying to put in SCE and SCE corr, I found very little difference in the sample having or not having the correction applied. It was not say 0 change for all showers, but in any case I wasn't sure if it should be as small a difference as it was. (just noted for future testing)

Also a few other things I believe I noticed from this test:
(1) This seemed to be running a different hit finding than I usually see. Was this intentional?
(2) I didn't scour the logs, mostly just was looking for it to have showers now. However, I think I noticed a few warnings/etc. from this test (I definitely noticed these, it's just a matter of it I noticed during _this_ test or another thing I was running, but I think it was this...)
* One was a warning that daqTrigger was invalid. Maybe related to using a particle gun generator fcl?
* "Failed to get GTruth object" - looks like while making a CAF file or one of the associated producer modules

2021-08-10 07:49 UTC, PetrilloAtWork commented
I have pushed configurations to generate proton-only cosmic rays with overburden based on the "standard" configuration.
Unfortunately something seems broken in my box... cosmic rays generation fails when it's time to pick CORSIKA files.

2021-08-10 22:22 UTC, jzennamo commented
I added a few missing generator level fcls needed for the August production and tested @PetrilloAtWork's proton-only cosmic configurations, things seem to be working!

2021-08-10 22:27 UTC, wesketchum commented
Ooof, there are a lot of changes in here. Hard to track.

Can I recommend we try to cut off additions on this PR, move this from draft to non-draft, and make new PRs for any changes?? @gputnam @SFBayLaser ?

2021-08-10 22:42 UTC, gputnam commented
Many of the changes are interrelated and making PR's on top of PR's can be its own mess. There are still a couple outstanding changes that need to be added (PMT + CRT reconstruction). I don't know if the inclusion of the CRT + PMT low-level (hit/flash) reconstruction will go in this PR or another. But once it is included I will also need to add in Iker's Flash matching to the high level reconstruction. So I don't think this PR is ready to move out of draft yet.

2021-08-12 22:35 UTC, gputnam commented
I have merged in two more feature branches: Tracy's to include latest updates to stage0 / stage1 processing and Jacob's to run Iker's flash matching. Should be ready! So I will make this not a draft anymore.

I do want to run a couple more tests before this is merged, but it is ready for review.

2021-08-13 15:26 UTC, jzennamo commented
This all looks awesome and I am really excited to have it merged in!

2021-08-14 05:02 UTC, PetrilloAtWork requested changes
My partial review (conflict of interest, remember?) found a couple of potential issues.

1. Naming of a few of new proton-only configurations does not follow the existing pattern.
2. Hard-coded numbers replicated around: _suggesting_ centralisation.
3. PMT decoding appears to have disappeared from one of the configurations.
4. one of the job configurations, `stage0_single_icarus.fcl`, seems to fail parsing.

Also there is material for a feature request to `GENIEGen` (it is possible to implement it without even changing `GENIEHelper`, which means that we can hope to see it soon).

2021-08-15 18:59 UTC, gputnam commented on fcl/caf/cafmakerjob_icarus.fcl
> +
Fixed.

2021-08-15 18:59 UTC, gputnam commented on fcl/caf/cafmakerjob_icarus.fcl
> +
Fixed the bad config -- although the block is used in one of the caf flavors so I am keeping it there.

2021-08-15 19:05 UTC, gputnam commented
Added some commits to address Gianluca's comment and add in CRT hits/tracks to CAF-making

2021-08-15 19:05 UTC, gputnam commented
Also I have run the tests that I wanted to!

2021-08-15 19:10 UTC, gputnam commented on fcl/gen/numi/simulation_genie_icarus_numi_volDetEnclosure_tpc.fcl
> +physics.producers.generator.FiducialCut: "mbox: -378.49,-191.86,-904.950652270838,378.49,144.96,904.950652270838"
We can include this as a future fix but it's still not clear to me that this is the best way to generate genie events in both cryostats, so I'd like to wait before optimizing the config.

2021-08-17 14:08 UTC, SFBayLaser commented
trigger build

2021-08-17 14:09 UTC, FNALbuild commented
CI build for LArSoft on slf7 for c7:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12249&builds=)

2021-08-17 14:09 UTC, FNALbuild commented
CI build for LArSoft on slf7 for e20:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12248&builds=)

2021-08-17 14:10 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12249&builds=)

2021-08-17 14:10 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12248&builds=)

2021-08-17 14:10 UTC, FNALbuild commented
CI build for ICARUS on slf7 for c7:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/2379&builds=)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12249&builds=)

2021-08-17 14:10 UTC, FNALbuild commented
CI build for ICARUS on slf7 for e20:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/2380&builds=)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12248&builds=)

2021-08-17 14:16 UTC, SFBayLaser approved these changes
I am already familiar with the bulk of the changes and have verified they are working. There are further updates that I think I need to see in action. So I will merge this and then run through my checks on my laptop.

2021-08-17 14:22 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase unit_test ICARUS on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/2379&builds=)

:rotating_light: For more details about the failed phase, check the [unit_test ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/2379&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=unit_test&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12249&builds=)

2021-08-17 14:22 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase unit_test ICARUS on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/2380&builds=)

:rotating_light: For more details about the failed phase, check the [unit_test ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/2380&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=unit_test&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12248&builds=)

2021-08-17 14:25 UTC, SFBayLaser commented
Ok, the expected outcome of the build since we are still getting things fixed there too. So will merge.

2021-08-17 14:25 UTC, merged