Updates FHiCLs for CAF to read weights from SBNEventWeight moduls in sbncode
SBNSoftware/icaruscode pull request #287
Opened 2021-11-09 16:39 UTC by Ooohu

Update `cafmaker_defs.fcl`: 

Change "eventweight_genie3_sbn_A.fcl" to "eventweight_genie_sbn.fcl";
Add "eventweight_flux_sbn.fcl"

2021-11-09 17:23 UTC, cjbackhouse requested changes

2021-11-09 17:23 UTC, cjbackhouse commented on fcl/caf/cafmakerjob_icarus_sce_genie_and_fluxwgt.fcl
> +physics.runprod: [ @sequence::caf_ana_sce_evtw_sequence, cafmaker, genieweight, fluxweight]
```suggestion
physics.runprod: [ @sequence::caf_ana_sce_evtw_sequence, genieweight, fluxweight, cafmaker ]
```
Pretty sure causes need to precede effects :wink:

2021-11-09 22:15 UTC, cjbackhouse approved these changes
Looks right to me, but we should check it actually runs.

2021-11-10 17:40 UTC, Ooohu commented
Tested. It runs!

2021-11-11 15:06 UTC, jzennamo approved these changes

2021-11-11 15:07 UTC, jzennamo commented
This addresses issue https://github.com/SBNSoftware/icaruscode/issues/250 and I think it is ready to go!

2021-11-15 18:11 UTC, FernandaPsihas approved these changes

2021-11-15 18:55 UTC, FernandaPsihas commented
@SFBayLaser, would it be possible to merge this before the 2021C freeze this week? Thank you!

2021-11-15 20:22 UTC, SFBayLaser commented
Yes, working on getting some stuff in for a release based on last week's LArSoft... at this rate hopefully tomorrow for that.

2021-11-17 19:46 UTC, merged

2021-11-17 21:02 UTC, SFBayLaser commented
Hi Folks, I should have done the old "trigger build" before I merged this PR... this PR is causing the CI tests to fail during the check fhicl stage, you can see the problem at https://dbweb8.fnal.gov:8443/LarCI/app/ns:icarus/storage/docs/2021/11/17/testFHiCLfiles_icarus.sh.log
I don't want to back this PR out... so can someone please very quickly take a look at this and fix? 
Thanks!

2021-11-18 05:18 UTC, Ooohu commented
> Hi Folks, I should have done the old "trigger build" before I merged this PR... this PR is causing the CI tests to fail during the check fhicl stage, you can see the problem at https://dbweb8.fnal.gov:8443/LarCI/app/ns:icarus/storage/docs/2021/11/17/testFHiCLfiles_icarus.sh.log I don't want to back this PR out... so can someone please very quickly take a look at this and fix? Thanks!

I fixed it here https://github.com/SBNSoftware/sbncode/pull/192#issuecomment-972546278
Basically I should have used the name `@local::sbn_eventweight_genie` all the time, but somehow I used `@local::sbn_genie_eventweight` (should have drop this) instead. That calls the variable defined here `sbncode/SBNEventWeight/jobs/genie/eventweight_genie_sbn.fcl`