cetmodules migration
SBNSoftware/icaruscode pull request #471
Opened 2022-10-19 03:08 UTC by gartung

2022-10-19 15:12 UTC, rennney commented
trigger build

2022-10-19 15:15 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17096&builds=)

2022-10-19 15:16 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17095&builds=)

2022-10-19 15:24 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5365&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5365&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=build&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17096&builds=)

2022-10-19 15:34 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5369&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5369&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=build&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17095&builds=)

2022-10-21 04:37 UTC, mmrosenberg commented
trigger build

2022-10-21 04:40 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17127&builds=)

2022-10-21 04:40 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17128&builds=)

2022-10-21 04:51 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5391&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5391&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=build&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17127&builds=)

2022-10-21 04:57 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5390&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5390&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=build&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17128&builds=)

2022-10-22 01:53 UTC, mmrosenberg commented
trigger build

2022-10-22 01:56 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17156&builds=)

2022-10-22 01:56 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17155&builds=)

2022-10-22 02:57 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5411&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5411&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17155&builds=)

2022-10-22 03:00 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5412&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5412&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17156&builds=)

2022-10-22 19:09 UTC, gartung commented
The cmake warnings are from the use of deprecated macros. For a complete migration more changes will be needed.

2022-10-28 21:26 UTC, gartung commented
trigger build

2022-10-28 21:29 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17224&builds=)

2022-10-28 21:29 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17225&builds=)

2022-10-28 21:31 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5456&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5456&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=build&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17224&builds=)

2022-10-28 21:31 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5457&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5457&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=build&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17225&builds=)

2022-10-28 21:44 UTC, gartung commented
trigger build https://github.com/SBNSoftware/icarus_signal_processing/pull/19 https://github.com/SBNSoftware/icarusalg/pull/62 https://github.com/SBNSoftware/icarusutil/pull/4

2022-10-28 21:47 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17226&builds=)

2022-10-28 21:47 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17227&builds=)

2022-10-28 21:49 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5458&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5458&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=build&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17227&builds=)

2022-10-28 21:49 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5459&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5459&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=build&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17226&builds=)

2022-10-28 21:50 UTC, gartung commented
trigger build https://github.com/SBNSoftware/icarus_signal_processing/pull/19 https://github.com/SBNSoftware/icarusalg/pull/62 https://github.com/SBNSoftware/icarusutil/pull/4 larsoft@v09_61_00

2022-10-28 21:53 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17229&builds=)

2022-10-28 21:53 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17228&builds=)

2022-10-28 21:55 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5461&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5461&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=build&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17229&builds=)

2022-10-28 21:55 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5460&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5460&platform=Linux%203.10.0-1160.71.1.el7.x86_64&phase=build&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17228&builds=)

2022-10-31 12:55 UTC, gartung commented
trigger build https://github.com/SBNSoftware/icarus_signal_processing/pull/19 https://github.com/SBNSoftware/icarusalg/pull/62 larsoft@v09_61_00

2022-10-31 13:29 UTC, gartung commented
trigger build https://github.com/SBNSoftware/icarus_signal_processing/pull/19 https://github.com/SBNSoftware/icarusalg/pull/62 LARSOFT_SUITE_v09_61_00

2022-11-02 19:17 UTC, chissg requested changes
Lots of comments, but most of them are recommendations rather than necessary _right now_. The caveats:

* Anything with a question mark should be addressed as a possible problem.
* Any remaining `include_directories()`, `link_directories()`. or `find_library()` calls could affect package relocatability.
* Any change to `PUBLIC` _vs_ `PRIVATE` dependencies could affect downstream use.

2022-11-03 13:55 UTC, gartung commented on icaruscode/Analysis/trigger/CMakeLists.txt
> +  SOURCE ${lib_srcs}
I found that art_make and cet_make are used because they do globbing.

2022-11-03 15:44 UTC, chissg commented on icaruscode/Analysis/trigger/CMakeLists.txt
> +  SOURCE ${lib_srcs}
Yeah, CMake guides consistently advise against this because it can cause hysteresis and hard-to-diagnose problems.

2022-11-03 15:49 UTC, chissg commented on icaruscode/Analysis/trigger/CMakeLists.txt
> +  SOURCE ${lib_srcs}
Feel free to resolve this and similar conversations as "no action needed at this time." The whole point of Cetmodules migration is that improvements can be implemented gradually without preventing continued development within the UPS ecosystem.

2022-11-03 16:49 UTC, gartung commented on CMakeLists.txt
> +  EXTRA_FLAGS -pedantic -I $ENV{CLANG_FQ_DIR}/include/c++/v1
I assume this is left over from some effort to compile with clang's libc++.

2022-11-03 16:50 UTC, gartung commented on icaruscode/Analysis/trigger/CMakeLists.txt
> +  SOURCE ${lib_srcs}
"no action needed at this time."

2022-11-03 16:50 UTC, gartung commented on icaruscode/CRT/CRTDecoder/CMakeLists.txt
> +		CRTMergePreProcessTrees.cxx
"no action needed at this time."

2022-11-03 16:51 UTC, gartung commented on icaruscode/CRT/CRTUtils/CMakeLists.txt
> +art_make_library(LIBRARY_NAME icaruscode_CRTUtils
"no action needed at this time."

2022-11-03 16:52 UTC, gartung commented on icaruscode/Decode/ChannelMapping/CMakeLists.txt
> +	EXCLUDE "PMTChannelMapDumper.cxx"
"no action needed at this time."

2022-11-03 16:56 UTC, gartung commented on icaruscode/Analysis/tools/CMakeLists.txt
> +cet_build_plugin(TrackHitEfficiencyAnalysis art::tool LIBRARIES ${TOOL_LIBRARIES})
Time constraints don't allow doing the addition of these keywords.

2022-11-03 18:14 UTC, gartung reviewed
@chissg I understand all of the comments. I think iterating on your suggestions may need to wait for a follow-up PR.

2022-11-03 19:39 UTC, gartung commented on CMakeLists.txt
> +set(ICARUS_FFTW_LIBRARIES PkgConfig::FFTW3F PkgConfig::FFTW3 PkgConfig::FFTW3Q PkgConfig::FFTW3L)
The code links against the float and double versions of the fftw library. The cetmodules FindFFTW.cmake appears to only allow one fftw target.

2022-11-03 19:44 UTC, gartung commented on CMakeLists.txt
> +set(ICARUS_FFTW_LIBRARIES PkgConfig::FFTW3F PkgConfig::FFTW3 PkgConfig::FFTW3Q PkgConfig::FFTW3L)
I see several calls based one from a dependency
```
-- Checking for one of the modules 'fftw3'
...
-- Checking for one of the modules 'fftw3f'
```

2022-11-04 16:13 UTC, gartung commented
trigger build SBNSoftware/icarus_signal_processing#18 SBNSoftware/icarusalg#62

2022-11-04 16:16 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17321&builds=)

2022-11-04 16:16 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17320&builds=)

2022-11-04 16:20 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5520&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5520&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=build&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17321&builds=)

2022-11-04 16:20 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5521&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5521&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=build&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17320&builds=)

2022-11-04 16:22 UTC, gartung commented
trigger build SBNSoftware/icarus_signal_processing#18 SBNSoftware/icarusalg#62

2022-11-04 16:32 UTC, gartung commented
trigger build SBNSoftware/icarus_signal_processing#18 SBNSoftware/icarusalg#62

2022-11-04 16:35 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17322&builds=)

2022-11-04 16:35 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17323&builds=)

2022-11-04 17:27 UTC, chissg commented on CMakeLists.txt
> +  EXTRA_FLAGS -pedantic -I $ENV{CLANG_FQ_DIR}/include/c++/v1
Even so, one should be adding the `-stdlib=libc++` flag instead.

2022-11-04 17:30 UTC, chissg commented on CMakeLists.txt
> +set(ICARUS_FFTW_LIBRARIES PkgConfig::FFTW3F PkgConfig::FFTW3 PkgConfig::FFTW3Q PkgConfig::FFTW3L)
Note that Cetmodules offers `FindFFTW3{f,l,q}.cmake` as symbolic links to `FindFFTW3.cmake`. Any or all (or none) of them can be invoked independently with `find_package()`

2022-11-04 17:30 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase ci_tests ICARUS on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5522&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5522&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17322&builds=)

2022-11-04 17:30 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase ci_tests ICARUS on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5523&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5523&platform=Linux%203.10.0-1160.71.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17323&builds=)

2022-11-04 17:49 UTC, chissg commented on CMakeLists.txt
> +find_package(Microsoft.GSL HINTS $ENV{GUIDELINE_SL_DIR})
Also `REQUIRED`

2022-11-04 17:52 UTC, chissg commented
@gartung, please address remaining (unresolved) review comments with question marks, and see if the FFTW3-related recommendations can be implemented easily.

2022-11-04 20:15 UTC, gartung commented
trigger build SBNSoftware/icarusalg#62 SBNSoftware/icarus_signal_processing#10

2022-11-04 20:19 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17345&builds=)

2022-11-04 20:19 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17346&builds=)

2022-11-04 21:20 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5539&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5539&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17345&builds=)

2022-11-04 21:22 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5540&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5540&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17346&builds=)

2022-11-10 15:15 UTC, gartung commented
trigger build

2022-11-10 15:56 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17428&builds=)

2022-11-10 15:57 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17429&builds=)

2022-11-10 15:58 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17431&builds=)

2022-11-10 15:58 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17430&builds=)

2022-11-10 16:48 UTC, gartung commented
I saw the error earlier after I merged `release/test_release_cetmodules` into `from-v09_60_01`. I found the issues and fixed them. merge in the current head of `from-v09_60_01` into `release/test_release_cetmodules`.

2022-11-10 17:49 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5596&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5596&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17428&builds=)

2022-11-10 18:05 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5597&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5597&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17429&builds=)

2022-11-10 18:29 UTC, rennney commented
iacruscode v09_62_00_02 that includes current develop+this PR is now on cvmfs. Same for icarusalg and icarus_signal_processing

2022-11-10 18:33 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5598&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5598&platform=Linux%203.10.0-1160.71.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17431&builds=)

2022-11-10 18:57 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5599&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5599&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17430&builds=)

2022-11-11 18:01 UTC, merged