Fixing CRTT0Matching_module
SBNSoftware/icaruscode pull request #508
Opened 2023-01-05 00:13 UTC by tboone0042

Replaces a now-faulty if statement to correctly search for the default value of DCA for the closest CRT Hit and skip if that default is found, which is a sign no match was found and thus will return null pointers that have caused seg faults.

2023-01-05 02:03 UTC, tboone0042 commented
this one should be based on _develop_

2023-01-05 22:58 UTC, PetrilloAtWork requested changes
The comment is the same as for PR #509, except that here there is no issue with the package versions.

I recommend that Tyler completes the work on that PR before this one be merged.
The reason is just that if he decides to change anything in there because of the review, those changes should be replicated here too.

If this PR stays identical to #509 then it's good to go at the same time the other one goes too.

2023-01-13 19:24 UTC, mmrosenberg commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

2023-01-13 20:51 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/18097&builds=)

2023-01-13 20:53 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/18096&builds=)

2023-01-14 00:06 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/6161&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/6161&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/18097&builds=)

2023-01-14 00:36 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/6162&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/6162&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/18096&builds=)

2023-01-14 02:46 UTC, merged