This commit includes the following features: Updated CRT-PMT matching…
SBNSoftware/icaruscode pull request #540
Opened 2023-03-02 10:53 UTC by francescopoppi

This PR is in parallel with: https://github.com/SBNSoftware/icaruscode/pull/539 (approved by the reviewers)

This PR contains 3 major elements:

1. An updated and improved CRT-PMT matching analysis tool (docDB 30190).
2. A bug fix that prevents stage0 failing with Runs after run number 9580. Starting from these runs, two additional spare Top CRT modules were included in the DAQ. The bug was due to the CRT decoder stage failing to find the cable delay of the 2 new modules since they were not present in the delay definitions. This patch includes the corresponding delays and prevents the failure of the Stage0 processing **_but_** the CRT hits coming from these two external modules will not be reconstructed since they cannot be matched with a module in the gdml geometry of ICARUS. I believe we do not want to include them in the simulation/gdml since they potentially will move around to sample different region of the detector roof (above concrete). There is a branch forked from develop where I am (succesfully) testing the reconstruction of these two modules to have the correspondent CRT hits available in the CRTHits data products, but more testing is foreseen. I expect at least one month of testing before releasing this feature, but nonetheless it is definitely not critical.
3. Previously the light propagation delay inside the WLS fibre was determined by using the light group velocity in the fibre, now we are using a data driven model that depends only by the triggering sector. See DodcDB 29504 slide 9. 

NOTE: The Top CRT modules can be represented as 64 triggering sector, depending only on the quadruplets of triggering channel.

2023-03-02 23:47 UTC, mmrosenberg commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_63_00 SBNSoftware/sbncode@v09_63_00_02 SBNSoftware/sbnanaobj@v09_20_00_01 SBNSoftware/sbndaq_artdaq_core@v1_04_02of0 SBNSoftware/sbnobj@v09_15_00_01 SBNSoftware/icarus_signal_processing@v09_63_00_02 SBNSoftware/icarusalg@v09_63_00_02p03 SBNSoftware/icarusutil@v09_62_00

2023-03-03 00:04 UTC, PetrilloAtWork requested changes
I have left a lot of coding comments that may be considered by the author (actually I suspect some of these pertain parts of code inherited from the older version...).
But I request two changes:
* the threshold value `400` be turned into a configurable parameter
* fix the bug highlighted in the comment

--- 

More in general, I feel like here this is material for algorithm code, not just an analyzer module.
This matching is useful enough that we'll want it encapsulated probably into a producer, and its result serialised into a data product. I am not sure how far we are from there.
Thus I have been pickier than my usual for analyzer modules.

2023-03-03 00:17 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/18622&builds=)

2023-03-03 00:21 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/18623&builds=)

2023-03-03 00:32 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/6599&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/6599&platform=Linux%203.10.0-1160.81.1.el7.x86_64&phase=build&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/18622&builds=)

2023-03-03 01:30 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/6600&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/6600&platform=Linux%203.10.0-1160.81.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/18623&builds=)

2023-03-03 10:13 UTC, francescopoppi commented
Right... as @PetrilloAtWork mentioned I forgot to merge comments addressed in previous (couple of months ago) PR which are included here: https://github.com/SBNSoftware/icaruscode/blob/develop/icaruscode/Filters/FilterCRTPMTMatching_module.cc
Today I will merge them all into this PR (and in the one for develop)

2023-03-03 10:59 UTC, francescopoppi commented on icaruscode/CRT/CRTPMTMatchingAna_module.cc
> +        fGeometryService->OpDetGeoFromOpChannel(hit->OpChannel()).GetCenter();
well... This is awkward. This is probably why I was getting weird values on the OpFlash barycenter.

2023-03-03 11:03 UTC, francescopoppi commented on icaruscode/CRT/CRTPMTMatchingAna_module.cc
> +        flash_pos[2]=flash_pos[2]+pos[2]*amp;
This toghether with the previous comment is wonderful.

2023-03-03 18:00 UTC, mmrosenberg commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_63_00 SBNSoftware/sbncode@v09_63_00_02 SBNSoftware/sbnanaobj@v09_20_00_01 SBNSoftware/sbndaq_artdaq_core@v1_04_02of0 SBNSoftware/sbnobj@v09_15_00_01 SBNSoftware/icarus_signal_processing@v09_63_00_02 SBNSoftware/icarusalg@v09_63_00_02p03 SBNSoftware/icarusutil@v09_62_00

2023-03-03 18:38 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/18645&builds=)

2023-03-03 18:53 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/18644&builds=)

2023-03-03 21:47 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/6620&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/6620&platform=Linux%203.10.0-1160.81.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/18644&builds=)

2023-03-03 21:47 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/6619&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/6619&platform=Linux%203.10.0-1160.81.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/18645&builds=)

2023-03-03 22:07 UTC, PetrilloAtWork commented
I have added a commit in agreement with @francescopoppi.

2023-03-03 22:08 UTC, PetrilloAtWork requested changes
A `cout` is left in there that should be removed or replaced.
I have left two more comments (and a commit :roll_eyes:).
The rest is good though.

2023-03-06 13:31 UTC, francescopoppi commented on icaruscode/CRT/CRTPMTMatchingAna_module.cc
> +          (Long64_t)m_trigger_timestamp - (Long64_t)m_gate_start_timestamp;
It is not. Removed redundat variable.

2023-03-06 13:32 UTC, francescopoppi commented on icaruscode/CRT/CRTPMTMatchingAna_module.cc
> +  for matched OpHit int            fTofTpcFlash;  //TPC for matched OpFlash
yes, but on top of that I removed the obsolete and commented tree structure

2023-03-06 18:36 UTC, mmrosenberg commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_63_00 SBNSoftware/sbncode@v09_63_00_02 SBNSoftware/sbnanaobj@v09_20_00_01 SBNSoftware/sbndaq_artdaq_core@v1_04_02of0 SBNSoftware/sbnobj@v09_15_00_01 SBNSoftware/icarus_signal_processing@v09_63_00_02 SBNSoftware/icarusalg@v09_63_00_02p03 SBNSoftware/icarusutil@v09_62_00

2023-03-06 19:23 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/18677&builds=)

2023-03-06 20:35 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/6647&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/6647&platform=Linux%203.10.0-1160.81.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/18678&builds=)

2023-03-06 20:35 UTC, PetrilloAtWork approved these changes
No more comments.
Hey, that's news.

2023-03-06 21:22 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/6652&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/6652&platform=Linux%203.10.0-1160.81.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/18677&builds=)

2023-03-06 21:54 UTC, merged