Added OpFlashes to SimpleFlash
SBNSoftware/icaruscode pull request #621
Opened 2023-08-15 21:41 UTC by Robert-Darby

- Added OpFlashes for SBND and ICARUS
- - 2 flashes/slice for ICARUS (simpleflash, opflash)
- - Seperate training metrics for each flash
- - Both flashes recorded in CAFs (rec.slc.fmatch/fmatchop)
- UseCollection fcl parameter changed to PlaneList - select which wire planes hits are selected from (all by default)

2023-08-15 21:47 UTC, Robert-Darby commented
Related PRs: 
icaruscode: https://github.com/SBNSoftware/icaruscode/pull/621
sbndcode: https://github.com/SBNSoftware/sbndcode/pull/381
sbncode: https://github.com/SBNSoftware/sbncode/pull/382
sbnanaobj: https://github.com/SBNSoftware/sbnanaobj/pull/107

2023-08-22 17:03 UTC, ikatza commented on fcl/configurations/flashmatch_simple_icarus.fcl
> +# BEGIN_PROLOG #comment to run generate_simple_weighted_template.py
This line shouldn't be commented.

2023-08-22 17:08 UTC, ikatza commented on fcl/configurations/flashmatch_simple_icarus.fcl
> +icarus_simple_flashmatch_W.OpFlashHitProducer: ["opflashCryoE"]
Shouldn't it be `opflashCryoW`?

2023-08-22 17:14 UTC, ikatza requested changes
Typos

2023-09-18 21:14 UTC, Robert-Darby commented
New metrics file (ready for merge) at:

2023-09-18 21:16 UTC, Robert-Darby commented
New ICARUS metrics file at: /icarus/data/users/rdarby/flashmatch/opflash/v09_77_00/train/FlashMatch

2023-10-10 16:31 UTC, ikatza approved these changes

2023-12-14 17:17 UTC, mmrosenberg commented
trigger build SBNSoftware/sbncode#382 SBNSoftware/sbnanaobj#107

2023-12-14 17:20 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21224&builds=)

2023-12-14 17:20 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21223&builds=)

2023-12-14 18:13 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase ci_tests ICARUS on slf7 for e26:prof - ignored failure for unit_test - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/8698&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/8698&platform=Linux%203.10.0-1160.99.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21224&builds=)

2023-12-14 18:46 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase ci_tests ICARUS on slf7 for c14:prof - ignored failure for unit_test - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/8699&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/8699&platform=Linux%203.10.0-1160.99.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21223&builds=)

2024-01-05 20:44 UTC, mmrosenberg commented
trigger build SBNSoftware/sbncode#382 SBNSoftware/sbnanaobj#107

2024-01-05 20:47 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21370&builds=)

2024-01-05 20:47 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21369&builds=)

2024-01-05 20:54 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/8840&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/8840&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21369&builds=)

2024-01-05 21:26 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e26:prof - ignored failure for unit_test - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/8839&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/8839&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21370&builds=)

2024-01-12 17:30 UTC, mmrosenberg commented
trigger build SBNSoftware/sbncode#382 SBNSoftware/sbnanaobj#107

2024-01-12 17:34 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21430&builds=)

2024-01-12 17:34 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21429&builds=)

2024-01-12 17:40 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/8884&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/8884&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21430&builds=)

2024-01-12 17:42 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/8883&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/8883&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=build&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21429&builds=)

2024-01-15 17:18 UTC, mmrosenberg commented
trigger build SBNSoftware/sbncode#382 SBNSoftware/sbnanaobj#107

2024-01-15 17:21 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21447&builds=)

2024-01-15 17:21 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21446&builds=)

2024-01-16 21:27 UTC, merged