Accommodate breaking changes for geometry refactoring
SBNSoftware/icaruscode pull request #642
Opened 2023-11-01 15:32 UTC by knoepfel

Accommodate changes from:

- https://github.com/LArSoft/larcoreobj/pull/19
- https://github.com/LArSoft/larcorealg/pull/37

----

**N.B.**: This PR should not be merged until the above PRs have been merged into a LArSoft release.

2024-12-04 21:03 UTC, mmrosenberg commented
trigger build SBNSoftware/icarusalg#75

2024-12-04 21:07 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24317&builds=)

2024-12-04 21:07 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24316&builds=)

2024-12-04 21:23 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase ci_tests ICARUS on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/11019&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/11019&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24316&builds=)

2024-12-04 21:27 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase ci_tests ICARUS on slf7 for c14:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/11018&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/11018&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24317&builds=)

2024-12-10 22:48 UTC, knoepfel commented
See https://github.com/LArSoft/larpandora/pull/43.  It's likely that the CI results will be more successful once that PR is adopted.

2025-01-27 16:51 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24762&builds=)

2025-01-27 16:52 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24761&builds=)

2025-01-27 17:04 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/11283&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/11283&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24762&builds=)

2025-01-27 17:21 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase ci_tests ICARUS on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/11284&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/11284&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24761&builds=)

2025-01-29 17:08 UTC, leoaliaga commented
trigger build SBNSoftware/icarusalg#75 LArSoft/lar*@LARSOFT_SUITE_v10_03_01

2025-01-29 17:20 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24805&builds=)

2025-01-29 17:21 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24804&builds=)

2025-01-29 17:46 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/11302&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/11302&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24804&builds=)

2025-02-05 00:05 UTC, gputnam reviewed
Only caught one possible issue! Although I did not look closely at PMT/CRT code.

2025-02-05 00:05 UTC, gputnam commented on icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
> -        if (position[2] < 0.5 * m_geometry->DetLength()) wireID.Wire = 0;
Not sure if these two lengths are the same in the updated v10 interface/

2025-02-05 14:28 UTC, knoepfel commented on icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
> -        if (position[2] < 0.5 * m_geometry->DetLength()) wireID.Wire = 0;
Yes, they are the same length.

2025-02-18 06:33 UTC, PetrilloAtWork requested changes
There are a few automatic replacements that should not have happened.
~Then there are the more important comments, but GitHub is not friendly in helping me find them, and it must have deleted my draft review already twice, so I'll refer to the comments directly.~ _[after submitting the review I can easily see my own comments all lined up]_

I thing there is a bug to be fixed.
One other comment requires the review of @SFBayLaser, whom I am adding to the reviewers and informing of this.

2025-02-18 06:33 UTC, PetrilloAtWork commented on icaruscode/TPC/Simulation/DetSim/tools/CoherentNoiseFactorProvider.cxx
Spurious changes, please revert.
`IICARUSChannelMap` is the service interface to a database relating the components of the hardware to the channels in LArSoft.

2025-02-18 06:33 UTC, PetrilloAtWork commented on icaruscode/TPC/Simulation/DetSim/tools/SBNDataNoise_tool.cc
Also spurious. Please revert.

2025-02-18 06:33 UTC, PetrilloAtWork commented on icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
> +        wireID.Wire = int(distanceToWire);
My reading of the code is that the former code was using rounding to the closest integer (inside `NearestWireID()`), while this is explicitly using truncation.
In addition, the original code can throw a (annoying) exception (`geo::InvalidWireError`, as described in the [documentation](https://code-doc.larsoft.org/docs/latest/html/classgeo_1_1PlaneGeo.html#a0f2906b4332d3eedc05c2191879a1ae4)), while here this will not happen.
That documentation also suggests a possible solution. The author of this code (@SFBayLaser?) should weigh in.

2025-02-18 06:33 UTC, PetrilloAtWork commented on icaruscode/Timing/PMTWaveformTimeCorrectionExtractor.cxx
Spurious changes. Please revert.

2025-02-18 06:33 UTC, PetrilloAtWork commented on icaruscode/Timing/PMTWaveformTimeCorrectionExtractor.h
One more spurious change to be reverted.

2025-02-18 16:35 UTC, SFBayLaser commented on icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
> +        wireID.Wire = int(distanceToWire);
Yes, the TODO in  the documentation would be an ideal solution!

2025-02-18 16:47 UTC, SFBayLaser commented on icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc
> +        wireID.Wire = int(distanceToWire);
Ok, I  went back to the original file to remind myself... there is a nearly decade long history here (from the early days of cluster3d) where there were issues, obviously, using the WireCoordinate method which were not understood (hence it being commented out). I am pretty sure this last configuration has been in place for around 5-6 years and I'd bet that now it could be done better... 
I'd accept the change for now, then we should compare this file against the one in sbncode, reconcile differences and then remove this from icaruscode. (and, really, we should update everything in larreco so it can be used for DUNE too since it seems someone has been picking it up).

2025-02-18 16:48 UTC, SFBayLaser approved these changes
I am ok with what I was asked to look at

2025-02-27 22:25 UTC, PetrilloAtWork commented on icaruscode/Timing/PMTWaveformTimeCorrectionExtractor.h
> +            icarusDB::IICARUSChannelMap const & wireReadoutService,
```suggestion
```

2025-02-27 22:27 UTC, PetrilloAtWork commented on icaruscode/Analysis/RawDigitAna_module.cc
> +        IRawDigitHistogramTool::SimChannelMap wireReadout;
```suggestion
        IRawDigitHistogramTool::SimChannelMap channelMap;
```

2025-02-27 22:28 UTC, PetrilloAtWork commented on icaruscode/Analysis/RawDigitAna_module.cc
> +            for(const auto& simChannel : *simChannelHandle) wireReadout[simChannel.Channel()] = &simChannel;
```suggestion
            for(const auto& simChannel : *simChannelHandle) channelMap[simChannel.Channel()] = &simChannel;
```

2025-02-27 22:28 UTC, PetrilloAtWork commented on icaruscode/Analysis/RawDigitAna_module.cc
> +            for(auto& rawDigitHistTool : fRawDigitHistogramToolVec) rawDigitHistTool->fillHistograms(clockData, detProp, allRawDigitVec,wireReadout);
```suggestion
            for(auto& rawDigitHistTool : fRawDigitHistogramToolVec) rawDigitHistTool->fillHistograms(clockData, detProp, allRawDigitVec,channelMap);
```

2025-02-28 04:27 UTC, PetrilloAtWork commented on icaruscode/Analysis/trigger/TimeTrackTreeStorageCRT_module.cc
> +  geo::GeometryCore const& geometry,
Ok, my guess is that it was changed not to interfere with another scripted replacement. I'll revert this one.

2025-02-28 04:34 UTC, PetrilloAtWork commented on icaruscode/Decode/ChannelMapping/Legacy/ICARUSChannelMapProvider.cxx
Spurious change.

2025-02-28 07:09 UTC, PetrilloAtWork approved these changes
I have integrated all the small changes and a bug fix in the branch.
There is still a pending question on a change that looks unnecessary and whose motivation is not clear.
Lacking understanding of the change, I have left the code as proposed by the submitter.
While these aspects are dealt with, I am ok for the PR to proceed.

2025-02-28 08:16 UTC, PetrilloAtWork requested changes
Finally rejecting this PR in favour of #808.

2025-03-03 19:03 UTC, merged