materials for the simulation of dirts BNB events added
SBNSoftware/icaruscode pull request #662
Opened 2024-01-25 18:58 UTC by cfarnese

I added here few things that can be used to produce dirt events for the BNB beam! The code I must confess is not so "beautiful" but I commit it in any case to try to have it for the new release! In particular there are :

- a couple of fhicl files in fcl/gen/genie to generate the dirts events

- a filter module and its fhicl to remove the neutrino interactions with the vertex inside the active volume or that did not deposit energy in the detector

2024-01-26 02:24 UTC, SFBayLaser commented
trigger build

2024-01-26 02:24 UTC, SFBayLaser commented
Interesting question... should we require "beauty" before we sign off on a PR?

2024-01-26 08:26 UTC, cfarnese commented
I believe usually the code should be clear and as simple as possible... I must confess in this case I prefer to make something "quick and dirt" because the main goal was to arrive in time and unfortunately the many activities don't provide me the proper time to make the code clearer.. sorry for this!

2024-01-26 17:21 UTC, mmrosenberg commented
trigger build

2024-01-26 17:24 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21589&builds=)

2024-01-26 17:24 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21588&builds=)

2024-01-26 18:03 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e26:prof - ignored failure for unit_test - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9008&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9008&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21589&builds=)

2024-01-26 18:21 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase ci_tests ICARUS on slf7 for c14:prof - ignored failure for unit_test - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9007&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9007&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21588&builds=)

2024-01-26 22:00 UTC, SFBayLaser approved these changes
Ok, quick and dirty… but approving!

2024-01-26 22:08 UTC, PetrilloAtWork requested changes
The name of `SimChannel` data product needs to be moved into a configuration parameter.
The rest are suggestions.

2024-01-26 22:08 UTC, PetrilloAtWork commented on icaruscode/Filters/FilterDirts_module.cc
> +#include "lardataobj/Simulation/SimPhotons.h"
Unused?
```suggestion
```

2024-01-26 22:08 UTC, PetrilloAtWork commented on icaruscode/Filters/FilterDirts_module.cc
> +#include "lardataalg/MCDumpers/MCDumperUtils.h" // sim::TruthXXXName()
Unused?
```suggestion
```

2024-01-26 22:57 UTC, PetrilloAtWork approved these changes
The comments from my previous review persist.
The submitter has explained me the role of `GenInTimeSorter`, which indeed hides a bug.
The sorter will take all generated stuff, cosmic rays from CORSIKA and neutrino interactions from GENIE, and will split them in "in time" and "out of time". The first category is then assumed to have been GEANT'd already, while the second category will be processed through GEANT4 in the next stage (e.g. `intime_g4_icarus.fcl`) and merged with the GEANT4 output of this stage.
The problem is that in-time cosmic rays, if any, will be assumed to have been processed already, while that's not the case (here GEANT4 only processed the neutrino events), resulting in the neutrino events never having a cosmic ray close in time.
The probability of such overlap is not large, though (10-kHz cosmic rays appear in a 2-µs gate once every 50 times).

With the submitter we agreed that the points raised in my review will be addressed ideally next week, and anyway in time for the production release. In the meanwhile, this PR should be merged as is in time for the _"intermediate"_ validation release.

**To the release managers: please do not delete the branch after merging.**

2024-01-29 15:52 UTC, cfarnese commented
I Introduce with the last commits almost all the corrections suggested by Gianluca! I tested this morning the code and it provides compatible results with respect to the previous version!

2024-01-29 16:43 UTC, mmrosenberg commented
trigger build

2024-01-29 16:46 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21625&builds=)

2024-01-29 16:46 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21626&builds=)

2024-01-29 16:50 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9043&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9043&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21625&builds=)

2024-01-29 21:30 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase ci_tests ICARUS on slf7 for e26:prof - ignored failure for unit_test - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9042&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9042&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21626&builds=)

2024-01-30 15:12 UTC, mmrosenberg commented
trigger build

2024-01-30 15:39 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21640&builds=)

2024-01-30 16:54 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase ci_tests ICARUS on slf7 for c14:prof - ignored failure for unit_test - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9057&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9057&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21640&builds=)

2024-01-30 16:57 UTC, merged