Feature/howard for nu mi2023 a from gputnam configs
SBNSoftware/icaruscode pull request #694
Opened 2024-02-18 17:43 UTC by brucehoward-physics

Cherry-picking in what I think are the relevant commits from Gray's feature branch used in the reprocessing.

A few minor edits where necessary to resolve a cherry-pick conflict may be present.

Actually I notice a few things here that relate to GENIE systematics, e.g. config_GENIEReWeightMultisigma_icarus_v2.fcl -- tagging @jedori0228 in case that is already in a commit he has on our board or this or others aren't needed or etc.

2024-02-19 16:30 UTC, jedori0228 commented
File changes under `fcl/caf/SystTools` are covered by https://github.com/SBNSoftware/icaruscode/pull/686

2024-02-19 20:20 UTC, brucehoward-physics commented
Merged Jaesung's feature branch into this -- this will facilitate testing and makes it slightly easier/fewer things.

2024-04-25 05:07 UTC, brucehoward-physics commented
I believe this should now have the geant4weight stuff removed. I pushed another branch `feature/howard_forNuMI2023A_from_gputnam-configs_WITHg4rw` which doesn't have these last 2 removal pieces.

2024-04-25 19:38 UTC, brucehoward-physics commented
Assigning a reviewer. Sorry Gianluca! 😬 😬

2024-05-03 00:37 UTC, PetrilloAtWork requested changes
I have left comments on the parts where my own expertise is not naught, but I can't review the systematics variations.
Somebody else should (@jzettle? @jedori0228?).

In general, there is some thing that DB people should cross check, and I would like references to be added to the numbers in the configurations.

2024-05-03 00:37 UTC, PetrilloAtWork commented on icaruscode/TPC/Calorimetry/normtools_icarus.fcl
> +  CalConstants: [1.0118, 1.0000, 1.0333, 1.0230]
Magic numbers! reference?

2024-05-03 00:37 UTC, PetrilloAtWork commented on icaruscode/TPC/ICARUSWireCell/detsimmodules_wirecell_ICARUS.fcl
> +icarus_simwire_wirecell_fitSR.wcls_main.structs.gain1: 12.6181926 # mV/fC
Reference?

2024-05-03 00:37 UTC, PetrilloAtWork commented on icaruscode/TPC/Calorimetry/normtools_icarus.fcl
> +icarus_data_calconst: [0.013316, 0.013316, 0.013316]
Reference?

2024-05-03 00:37 UTC, PetrilloAtWork commented on icaruscode/TPC/Calorimetry/normtools_icarus.fcl
> +# icarus_calonormtools: [@local::driftnorm_sql, @local::yznorm_sql, @local::tpcgain_sql]
Maybe @jedori0228 or @SFBayLaser can comment on this change? I suppose it is either very right or very wrong, but I never remember which one.

2024-05-03 00:37 UTC, PetrilloAtWork commented on icaruscode/TPC/Calorimetry/NormalizeTPC_tool.cc
> +  ScaleInfo i = GetScaleInfo(e.id().runID().run());
Skip the middle men!
```suggestion
  ScaleInfo i = GetScaleInfo(e.run());
```

2024-05-03 00:37 UTC, PetrilloAtWork commented on icaruscode/TPC/Calorimetry/NormalizeYZ_tool.cc
> +    return fScaleInfos.at(run);
Or:
```suggestion
    return fScaleInfos[run] = thisscale;
```
(but it may confuse people)

2024-05-03 00:37 UTC, PetrilloAtWork commented on icaruscode/TPC/Calorimetry/NormalizeYZ_tool.cc
> +  return fScaleInfos.at(run);
As above:
```suggestion
  return fScaleInfos[run] = thisscale;
```

2024-05-23 10:19 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/22863&builds=)

2024-05-23 10:19 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/22864&builds=)

2024-05-23 10:20 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9986&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9986&platform=Linux%20slf7&phase=build&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22863&builds=)

2024-05-23 10:20 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9987&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9987&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22864&builds=)

2024-05-23 10:34 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/22865&builds=)

2024-05-23 11:06 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e20:prof - ignored failure for unit_test -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9989&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9989&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22865&builds=)

2024-05-24 20:54 UTC, PetrilloAtWork approved these changes
Looks good. :crossed_fingers:

2024-05-30 20:00 UTC, merged