Added trigger logic information to PMT decoder diagnostic ROOT tree
SBNSoftware/icaruscode pull request #723
Opened 2024-03-27 04:36 UTC by PetrilloAtWork

With the new adder-based trigger, the PMT diagnostic tree should know whether the light collected at beam gate was coming from an adder or a majority trigger.
This commit adds that information to the tree, one piece of information per cryostat, directly from the trigger information.

_Edit_: it also adds a count of triggers from the beginning of the run and the gates from the previous trigger. This tree is being used for trigger studies as well.
_And_ a job configuration to create such trees, for the benefit of grid jobs.

Reviewer: @mvicenzi as PMT decoder insider.

2024-03-27 14:16 UTC, mvicenzi requested changes
I'm confused... it seems the updated code was already in develop and now you are removing it?

2024-03-27 14:16 UTC, mvicenzi commented on icaruscode/Decode/DaqDecoderICARUSPMT_module.cc
> -  tree->Branch("triggerLocation", &data.triggerLocation);
Ehm... it seems you are removing that information, instead of adding it?

2024-04-03 01:08 UTC, PetrilloAtWork commented
:flushed:
There was clearly an issue with my final branching (noted the three PR in a row coming from the same working area?). In fact, I pretty much lost the source of this PR, except that luckily I had tarballed it for grid jobs.

I have updated it now... thank you for catching this!!

There may or may not be a following commit rebasing this same code to the current `develop` branch.

2024-04-03 02:21 UTC, mvicenzi approved these changes
Way better now!

2024-04-03 02:21 UTC, mvicenzi commented on fcl/reco/Stage0/Run2/partial/decodePMT_icarus_treeonly.fcl
> +# The log file also dump the trigger information.
```suggestion
# The log file also dumps the trigger information.
```

2024-04-03 02:21 UTC, mvicenzi commented on fcl/reco/Stage0/Run2/partial/decodePMT_icarus_treeonly.fcl
> +# The noticeable exception is PMT raw waveforms not the corrections:
```suggestion
# The noticeable exception is PMT raw waveforms and the corrections:
```

2024-04-03 19:53 UTC, mmrosenberg commented
trigger build

2024-04-03 19:56 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/22343&builds=)

2024-04-03 19:56 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/22342&builds=)

2024-04-03 19:58 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9605&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9605&platform=Linux%203.10.0-1160.105.1.el7.x86_64&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22343&builds=)

2024-04-03 19:58 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9606&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9606&platform=Linux%203.10.0-1160.105.1.el7.x86_64&phase=build&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22342&builds=)

2024-04-03 21:22 UTC, mmrosenberg commented
trigger build

2024-04-03 21:25 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/22354&builds=)

2024-04-03 21:25 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/22355&builds=)

2024-04-03 21:35 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9617&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9617&platform=Linux%203.10.0-1160.105.1.el7.x86_64&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22354&builds=)

2024-04-03 22:04 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase ci_tests ICARUS on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9618&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9618&platform=Linux%203.10.0-1160.105.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22355&builds=)

2024-04-05 20:14 UTC, mmrosenberg commented
trigger build

2024-04-05 20:17 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/22401&builds=)

2024-04-05 20:17 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/22400&builds=)

2024-04-05 20:24 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9658&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9658&platform=Linux%203.10.0-1160.105.1.el7.x86_64&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22400&builds=)

2024-04-05 21:14 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9657&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9657&platform=Linux%203.10.0-1160.105.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22401&builds=)

2024-04-05 21:42 UTC, merged