Introduction of CRTT0Tagging module.
SBNSoftware/icaruscode pull request #774
Opened 2024-10-23 17:44 UTC by francescopoppi

This PR introduce a new producer module: CRTT0Tagging
This new module produces an association with tracks and and a T0 object following CRT-TPC association. It also fills a new icarus only data product with some summary information on the result of the match, this product is called CRTTPCMatchingInfo.
Additionally associations of anab::T0 and tracks and CRT and CRTTPCMatchingInfo are stored.
This PR introduces also the CRTMatching class which contains the matching functions. In future, TripleMatching will exploits the same functions, this is why, for example, there is the GetTrackBarycenter function which is not yet used.
A brief story: there is an already existent CRTT0Matching object, but that is very outdated and not mantained anymore. The problem is that that product is widely used around our code. Not to create confusion, I added here the updated version under a new name. The new matching is based on a PCA fit of the track direction and extrapolated to the CRT plane of the CRT hit under test.
At the state of this PR, the module lives on its own and it is not included into any stage0/1/caf definitions. It is there for people to use if needed. I will follow up, once this PR is considered ok, with an additional one which starts to implement the CRTTagging of the TPC tracks in our production and analysis flow.
This module works on both data and MC! The only caveat is that for data there is an additional implementation which re-align the Top CRT modules to the TPCs, following to the alignment campaign which I performed on Run2 data. It is expected that for Run3 a new alignment txt file will be produced, but I do not have yet since we did not reprocess Run3, so using the Run2 one is way better than not using it. 
I believe this SBN DocDB summarizes everything that it is introduced here: https://sbn-docdb.fnal.gov/cgi-bin/sso/RetrieveFile?docid=38008&filename=TPCCalibrationWithCRTTPCTaggedTracks.pdf&version=1

2025-01-08 08:14 UTC, PetrilloAtWork requested changes
I have left `std::numeric_limits<std::int8_t>::max()` comments.
The most relevant is that I am confused about the new data product compared to the old one: same name, completely different content, deceiving schema evolution.
It may be that you had already explained that, if so I can't find where.

I am of course available for helping with the resolution of the comments.

2025-01-13 11:50 UTC, francescopoppi commented on icaruscode/CRT/CRTUtils/CRTMatchingUtils.cxx
> +        fTickAtAnode = pset.get<double>("TickAtAnode", 850.);
Yes, I would like to specify them. For example, if empirically it is found that due to some cable the delay, the tic changes to 849 (e.g.) I would like for this to be configurable.
The TicPeriod I agree is not needed. Does it come from DetectorProperties?

2025-01-13 13:43 UTC, francescopoppi commented on icaruscode/CRT/CRTUtils/CRTMatchingUtils.h
> +    TrackBarycenter GetTrackBarycenter(std::vector<float> hx, std::vector<float> hy, std::vector<float> hz, std::vector<float> hw);
You are right, this is not used _yet_ ... The Util file is called CRTMatchingUtils and it will also include triple-matching related functions which will be implemented in different PR following this one. So, since (counterintuitively) I started working on this PR after developing the Triple-Matching one, I thought to start already including functions which will be used later on.

2025-01-13 13:48 UTC, francescopoppi commented on icaruscode/CRT/CRTUtils/CRTMatchingUtils.h
> +    CrossPoint DetermineProjection(const Direction& dir, CrtPlane plane);
I.... agree... did I add the dotted points suggesting my mental damage yet? ...
Somehow, in my mental chaos, this had some sort of sense and when trying to express it in an easier way, what you suggested sounded more complicate in my damaged brain.
But (geo::)point and suggestion taken.
I will come back to reorganizing this part after the other faster to address comments.

2025-01-13 13:52 UTC, francescopoppi commented on icaruscode/CRT/CRTUtils/CRTMatchingUtils.cxx
> +            if(loc.X()==-999) continue;
no and I am commenting it out. Commenting and not removing it because I think at some point I added it for debug and I don't recall why. I'll just leave it there for my future self trying to debug possible issues.

2025-01-14 14:53 UTC, francescopoppi commented on icaruscode/CRT/CRTT0Tagging_module.cc
> +      fTRKHMproducer(p.get< art::InputTag   > ("TRKHMproducer", "")),
With no shame, I admit I copied good part of this first part from the TrackCaloSkimmer Object.
What you are saying is right. What actually happens is that since fTRKHMproducerLabel.empty() it will use the TPCTrackLabel.
Can I leave it this way? In case in future there will be different TRKHMproducer from the the TPCTrackLabel ones.

2025-01-16 10:17 UTC, francescopoppi commented on icaruscode/CRT/CRTUtils/CRTMatchingUtils.cxx
> +        int outBound=0;
ok you win. I do not need it. removed the configurable parameters and added to the function detClocl

2025-01-16 10:19 UTC, francescopoppi commented on icaruscode/CRT/CRTT0Tagging_module.cc
> +      for ( auto const& channel : (*auxDetSimChannelHandle) ){
If there is, I am not aware, therefore I never used it

2025-01-16 10:21 UTC, francescopoppi commented on icaruscode/CRT/CRTT0Tagging_module.cc
> +      for ( auto const& channel : (*auxDetSimChannelHandle) ){
Anyway, the CRT channels are 32 and ideally the hit is associated to 4 channels.

2025-01-16 10:37 UTC, francescopoppi commented on icaruscode/CRT/CRTUtils/CRTMatchingUtils.cxx
> +        fTickAtAnode = pset.get<double>("TickAtAnode", 850.);
change of plan. removed.

2025-01-16 11:49 UTC, francescopoppi commented on icaruscode/CRT/CRTUtils/CRTMatchingUtils.cxx
> +            else if(cryo==1 && (tpc==2 || tpc==3)&& (X<(cathode-fAllowedOffsetCM)||X>(plane+fAllowedOffsetCM))) outBound++;
I have a proposed change, following our discussion on Slack. I think this is more elegant.
`            double AllowedRel = 1+fAllowedOffsetCM / abs(tpcGeo.GetCathodeCenter().X()-tpcGeo.PlanePtr(trkHits[i]->WireID().Plane)->GetCenter().X());
            if(!tpcGeo.ActiveBoundingBox().ContainsX((X), AllowedRel)) outBound++;`
            però vorrei mantenere il parametro di configurazione (allowed offset) in cm

2025-04-22 23:39 UTC, leoaliaga commented
Just a follow-up on this PR needed for the Spring production. It looks like the review comments have been addressed. 
@PetrilloAtWork, @gputnam: are there any remaining concerns from the reviewers?
@francescopoppi: there's currently a conflict in CMakeLists.txt that needs to be resolved.

2025-04-23 22:24 UTC, gputnam commented
@leoaliaga the PR looks good to me.

2025-04-24 17:56 UTC, PetrilloAtWork commented
I have put this as draft to highlight that it should not be merged as is (in fact, it should not be merged at all since it's superseded by #814).

2025-05-13 21:19 UTC, gputnam commented
Closing in favor of https://github.com/SBNSoftware/icaruscode/pull/814, now merged.

2025-05-13 21:19 UTC, closed without merging