Changes needed for YZ simulation
SBNSoftware/icaruscode pull request #784
Opened 2024-12-09 03:59 UTC by jzennamo

This PR will enable the variation of the signal shapes and gain across the YZ plane as measured for Run2. The support is in here to also model the electron lifetime separately in each cryostat (or TPC, or YZ bin). 

To fully use all these features the following PRs will also be required to be merged:
- [ ] icarus_data: feature/zennamo_yzsim
- [ ] larwirecell: feature/jzennamo_wct_yzsim_update
- [ ] lardataobj: feature/wketchum_FixSimChannelMerge
- [ ] wire-cell-toolkit: jzennamo:feature/jzennamo_yzsim_updated

This simulation has been validated by @gputnam and @mrmooney (Thanks!)

This might require a patch once we reorganize all of our fcl files but the base line simulation is intended to consume "shifted" SimEnergyDeposits from the refactored LArG4.

2024-12-11 18:44 UTC, SFBayLaser reviewed
At this point I believe this PR is being held captive waiting for the updated WireCell Toolkit.

2024-12-19 02:38 UTC, gputnam commented on icaruscode/TPC/ICARUSWireCell/detsimmodules_wirecell_ICARUS_YZsim.fcl
Looks good! One note here -- we'll have to tune time_offset_{u, v, y} parameters with the new signal shape simulation going in. Not something that should hold up the PR, but a validation step we should do once we merge it in. @brucehoward-physics has a study we did to do this previously.

2024-12-19 02:51 UTC, gputnam requested changes
Looks great overall! Couple questions / suggestions. Could also be ignored to merge in if there is urgency.

2024-12-19 02:51 UTC, gputnam commented on icaruscode/TPC/ICARUSWireCell/detsimmodules_wirecell_ICARUS_YZsim_shifted.fcl
Is the only difference here the "-shifted" jsonnet? Could you #include the base file instead and override this parameter?

2024-12-19 02:51 UTC, gputnam commented on icaruscode/TPC/ICARUSWireCell/icarus/funcs.jsonnet
I won't hold this up, but I'm pretty sure you could clean up this code with some std.range calls: https://jsonnet.org/ref/stdlib.html.

2024-12-19 02:51 UTC, gputnam commented on icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel-yzsim-refactored.jsonnet
Ok another note here (which should not hold up the review). We'll need to replace these with the ICARUSDrifters that I made (https://github.com/SBNSoftware/icaruscode/pull/782) to lookup the electron lifetime from the SQLite file.

2024-12-19 02:51 UTC, gputnam commented on icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel-yzsim-refactored.jsonnet
> +			 bin_width:  10*wc.cm,
How does this handle depositions that are outside the binning of the YZ maps? I don't think I included the whole TPC when I made those.

2024-12-19 02:51 UTC, gputnam commented on icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel-yzsim-shifted-refactored.jsonnet
What's the difference between this config and the non-shifted one?

2024-12-19 02:51 UTC, gputnam commented on icaruscode/TPC/ICARUSWireCell/icarus/wcls-multitpc-sim-drift-simchannel-yzsim.jsonnet
Is this one not -refactored? Do we need it? I don't see it referenced by a fcl file.

2025-04-23 17:45 UTC, SFBayLaser commented
another question, given a pending WireCell toolkit change... is this PR in need of that update or can it go ahead?

2025-04-23 22:25 UTC, gputnam commented
The PR is ok to me even without the comments being resolved.

2025-04-25 22:26 UTC, closed without merging